# Generated by Django 5.1.3 on 2024-11-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_employe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeconge',
            old_name='type_congee',
            new_name='type_conge',
        ),
        migrations.AddField(
            model_name='employe',
            name='photo_profil',
            field=models.CharField(default='https://www.freepik.com/premium-vector/default-profile-picture-ui-element-template_44646706.htm', max_length=1000),
        ),
    ]
