# Generated by Django 5.1.3 on 2024-11-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_type_congee_demandeconge_type_conge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=800)),
                ('task_description', models.CharField(max_length=10000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
