# Generated by Django 5.1.3 on 2024-11-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_createtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=800)),
                ('task_description', models.CharField(max_length=10000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.createtask')),
            ],
        ),
    ]
