# Generated by Django 5.1.3 on 2024-11-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_viewtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconge',
            name='motif',
            field=models.CharField(choices=[('Arrêt Maladie', 'Arrêt Maladie'), ('Congé sans solde', 'Congé sans solde'), ('Congé de maternité', 'Congé de maternité'), ('Congé de paternité', 'Congé de paternité'), ('Formation', 'Formation'), ('Autre Raison', 'Autre Raison')], max_length=100),
        ),
    ]
