# Generated by Django 5.1.3 on 2024-11-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_demandeconge_motif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeconge',
            name='type_conge',
        ),
    ]
